[package]
name = "builder"
version = "0.1.0"
edition = "2024"

[dependencies]
lucy_embedded_firmware_core = { path = "../lucy_embedded_firmware_core", features = ["serde"] }
heck = "0.5.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
syn = "2.0"
