//! Per-board register layout. Generated by lucy_config_generator for rp2040_so_arm — do not edit.

/// Registers per bus-servo block: id, angle, cmd.
pub const BUS_SERVO_BLOCK: u16 = 3;

pub const BUS_SERVO_BASE: u16 = 0;

pub const BUS_SERVO_SLOTS: u16 = 6;
