[package]
name = "lucy_embedded_firmware_rp2040_i2c_pwm"
version = "0.1.0"
edition = "2024"

[dependencies]
lucy_embedded_firmware_core = { path = "../../crates/lucy_embedded_firmware_core" }
cortex-m = "0.7.9"
cortex-m-rt = "0.7.6"
panic-halt = "1.0.0"
rp2040-boot2 = "0.3.0"
rp2040-hal = { version = "0.11.0", features = ["rt", "critical-section-impl"] }

[build-dependencies]
builder = { path = "../../crates/builder/" }
