[package]
name = "lucy_embedded_firmware_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
lucy_embedded_firmware_core = { path = "../../crates/lucy_embedded_firmware_core" }
crc = "3.4.0"
modbus-core = "0.2.0"
serialport = "4.10.0"
memmap2 = "0.9.11"
libc = "0.2.189"
zerocopy = "0.8.57"
bytemuck = "1.25.2"
